spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/todo
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-23-20-224-166.compute-1.amazonaws.com:5432/des6hol5afnuot
    username: rnqhfnfisldwhd
    password: dd2ab6105ec2c7a264823c1950439b00b98a937bb4a88bafd2a4558a5c157b4d

#  flyway:
#    password: postgres
#    user: postgres
#    url: jdbc:postgres://localhost:5432/todo
#    locations: filesystem:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  messages:
    always-use-message-format: true
